auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Noyllopa's Blog
url: https://noyllopa.github.io/
feed: /atom.xml
author_info: <a href="https://noyllopa.github.io/">Noyllopa</a>
