title: Noyllopa's Blog # your site title
author: GitHub User
email: noyllopa.rain@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Noyllopa的个人博客，包括游戏、动画、手机、科技等自己感兴趣的东西。
baseurl: "/" # the subpath of your site, e.g. /blog
url: "noyllopa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Noyllopa # replace with your_twitter_username or comment to remove link from footer
github_username:  Noyllopa # replace with your_github_username or comment to remove link from footer
social:
  name: Noyllopa
  links:
    - https://twitter.com/Noyllopa
    - https://weibo.com/noyllopa
    - https://noyllopa.lofter.com/

disqus:
  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
